trigger:
- develop

variables:
  appRepo: api-sys-oauth
  appBranch: develop
  scriptsRepo: azure-pipeline-mtc
  populatePomVarsScript: "populatePomVars.ps1"
  populatePomVarsScriptFolder: "powershell"
  artifactCollectionName: buildArtifacts
  anypointDeployScript: "bashArgValidate.sh"
  anypointDeployScriptFolder: "bash"
  pomName: pom.xml

pool:
  vmImage: 'windows-2019'

resources:
 repositories:
   - repository: templates
     type: git
     name: Mulesoft/azure-pipeline-mtc
     ref: master

stages: 
- template: pipelineStages.yml@templates


