name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  call-workflow:
    uses: Hemanth-sep29/privateSpace.git/.github/workflows/reusableWorkflow.yml@main
    secrets: inherit
